Add support for configurable job uniqueness.
ubccr/supremm pull request #265
Opened 2023-05-08 17:56 UTC by jpwhite4

This is needed for proper job array support see also pull requests in the xdmod and xdmod-supremm and xdmod-xsede code base.

2023-05-18 17:53 UTC, connersaeli commented
xdmod: https://github.com/ubccr/xdmod/pull/1723
xdmod-supremm: https://github.com/ubccr/xdmod-supremm/pull/327
xdmod-xsede: https://github.com/ubccr/xdmod-xsede/pull/400

2023-05-25 16:18 UTC, connersaeli requested changes

2023-05-26 19:06 UTC, jpwhite4 commented on config/config.json
> +            "job_uniq_mode": "local_job_id",
Ok. Plan is to autodetect the job unique identifier - no need for a configuration setting.

2023-05-26 19:16 UTC, connersaeli commented on src/supremm/xdmodaccount.py
> +                    END AS job_uniq_id,
Does `job_uniq_id` need to be \``job_uniq_id`\` (with backticks)? Or is that a bit pedantic? Just thinking if it should match the syntax for the other aliases.

2023-05-26 19:16 UTC, connersaeli commented on src/supremm/xdmodaccount.py
> +                    END AS job_uniq_index,
Same comment here as line 31.

2023-05-26 19:43 UTC, connersaeli approved these changes

2023-05-26 19:53 UTC, merged